packaging_format = 2

id = "my_webapp"
name = "note"
description.fr = ""

version = "1.0"

maintainers = []

[upstream]
license = "GPL-3.0-only"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/site"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.custom_error_file]
    ask.en = "Activate the custom error file use"
    ask.fr = "Activer l'utilisation du fichier d'erreur personnalisé"
    type = "boolean"
    default = false
    help = "Once custom error enabled, you can add/create a custom `404.html` file in a directory `www/error`."

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "nginx"  # Kind of "dummy" value to be sure to have a non-empty dep list
    packages_from_raw_bash = ""
