#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
domain=$(ynh_app_setting_get --app=$app --key=domain)
path=$(ynh_app_setting_get --app=$app --key=path)

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__password() {
  if [ ! "$password" == "" ]; then
    ynh_app_setting_set --app=$app --key=password --value="$password"
  fi
}

#=================================================
# GENERIC FINALIZATION
#=================================================

ynh_app_config_validate() {
  _ynh_app_config_validate

}

ynh_app_config_apply() {
  _ynh_app_config_apply

  if [ "${changed[custom_error_file]}" == "true" ]; then
    CUSTOM_ERROR_FILE=$custom_error_file
    nginx_extra_conf_dir="/etc/nginx/conf.d/$domain.d/$app.d"

    if [ $custom_error_file -eq 1 ]; then
      ynh_add_config --template="nginx-code-error.conf" --destination="$nginx_extra_conf_dir/error-code.conf"
    elif [ $custom_error_file -eq 0 ]; then
      ynh_secure_remove --file="$nginx_extra_conf_dir/error-code.conf"
    fi
    ynh_systemd_action --service_name=nginx --action=reload
  fi

}

ynh_app_config_run $1
